### ISSUE TITLE
Unexpected behavior of a zero-weighted edge with delay

### ISSUE THREAD

**Issue by ffriese** [pyrates-neuroscience/PyRates#26]
Dear PyRates developers,

after successfully reproducing Figure 5 from the David and Friston paper with @Richert's great help in [this github issue](https://github.com/pyrates-neuroscience/PyRates/issues/25), I ran into another problem while reproducing Figure 6 from the same paper.

I created two areas, each made up of the subpopulation model from Figure 5, added some variables to the `RPO_e_pc` Operator:
```python
{
    'ext': {'default': 'input'},
    'n': {'default': 'variable'},
    'v_d1': {'default': 'variable'},
    'v_mean': {'default': 'variable'},
    'v_d2': {'default': 'variable'},
    'v_m2': {'default': 'variable'},
    'ext_variance': {'default': 'variable'},
    'k': {'default': 0.0}
}
```

added additional edges between the areas:
````python
edges.append((f"PC0/PRO_pc/m_out", f"PC1/RPO_e_pc/ext", None, {'weight': 1.0, 'delay': 0.001, 'spread': 0.0005}))
edges.append((f"PC1/PRO_pc/m_out", f"PC0/RPO_e_pc/ext", None, {'weight': 1.0, 'delay': 0.001, 'spread': 0.0005}))
````

replaced the input equation in the `RPO_e_pc` Operator to weigh the inputs according to the connectivity parameters `k` (and the derived `k*`, as defined in the paper):
````python
equations={'replace': {'m_in': '(m_in+(ext*(22.0*sqrt(2*k-k**2))/max(sqrt(ext_variance),1))+(u*(1-k)))'}}
````

and implemented an algorithm to iteratively calculate the sample variance of the external input `ext` (which is necessary for determining `k*`) in an incredibly hacky but apparently working way (any suggestions on how to do this differently, preferably without all those helper variables, is welcome) 
````python
equations = [
    'n = n + 1',
    'v_d1 = ext - v_mean',
    'v_mean = v_mean + v_d1 / (max(n,2) - 1)',
    'v_d2 = ext - v_mean',
    'v_m2 = v_m2 + v_d1*v_d2',
    'ext_variance = v_m2 / (max(n,3) - 2)',
]
````

This appeared to be working to some extent, as I received the expected synchronized signals (after giving the system a couple of seconds to converge) when connecting the areas bi-directionally with `k1=k2=0.5`, and increased the edge weights to values around 3.5 (I did not find any specific values for this anywhere, but weight 1.0 did not seem to work) .

However, when testing conditions with uni-directional (`k1=0.5, k2=0.0`) or zero-weighted (`k1=k2=0.0`) connections, 
I received strange results, where areas that had their external input multiplied by zero started to behave differently than they would on their own. Also for some reason the order in which the areas were defined appeared to have an impact on the results.

I figured out that this behavior only emerged when using the `delay` parameter in the edge, and that it did not matter whether the variable that the connection was fed into was actually used.

In the table below, I plotted 6 conditions, all of which would be expected to produce results identical to each area being simulated on its own.
The additional equations and variables described above were removed to single out the problem, except for the edge-input `ext`, 
which was however not replaced into the `m_in` calculation, but received a dummy equation `ext = ext`, removing (in my expectaion) its influence on the system.

The first column of the table shows how the two areas behave without any edge defined between them, producing the expected signals and spectra. 
The bottom row shows the results when the areas are flipped, and the top right graph illustrates the main problem arising when using the edge delay (while the flipped condition in the bottom right corner works roughly as expected for some reason in this particular case).

..|Without Edges | Edges (weight 0.0, delay 0.000) | Edges (weight 0.0, delay 0.001)
------------ | ------------- | ------------- | -------------
**Fast Area first** |![no_connection1](https://user-images.githubusercontent.com/28440404/121400375-cf2b6f00-c957-11eb-8816-3a3105aac913.png) | ![zero_weight_connection1](https://user-images.githubusercontent.com/28440404/121400431-dce0f480-c957-11eb-8945-ed7dcad2c059.png)| ![zero_weight_connection_delay1](https://user-images.githubusercontent.com/28440404/121400465-e702f300-c957-11eb-9738-35150ed33a68.png)
**Slow Area first**|![no_connection2](https://user-images.githubusercontent.com/28440404/121400927-701a2a00-c958-11eb-9a72-58152b464bc7.png) | ![zero_weight_connection2](https://user-images.githubusercontent.com/28440404/121400951-77d9ce80-c958-11eb-9a1f-f0f1858ea988.png) | ![zero_weight_connection_delay2](https://user-images.githubusercontent.com/28440404/121400970-7e684600-c958-11eb-8701-76568a0b1a32.png)

In my understanding this is not the expected behavior of a zero-weighted edge with a delay. 
Do I have any misconceptions on that or is it possible that I am using the edges incorrectly?

Thanks in advance for any insights on the matter.

**Comment by Richert** [comment]
Dear @ffriese 

thank you for bringing this issue to our attention. I am not immediately sure whats going south in this example. 
Could you provide the code of a minimal example, so I can have a look at it? I am specifically interested in how the model templates are defined and whether the parameter adjustments are realized via the `grid_search` function.

As a general comment on your problem, I suggest to refrain from using this helper variable implementation. These variable updates all depend on `n` which apparently just counts the number of integration steps and thus the whole model strongly depends on the integration step-size. Of course, this problem already exists in the model definition provided in David and Friston (2003). I suggest a slight alteration, which should converge to their implementation in some limit, but is better suited in a framework of coupled differential equations.

David and Friston state in their paper that 

> Practically, the values of k_12 were updated at each time step using the sample variance of S3(y1) over previous time steps (similarly for k21).

I assume that they actually mean that they updated <img src="https://render.githubusercontent.com/render/math?math=k_{12}^*"> and not <img src="https://render.githubusercontent.com/render/math?math=k_{12}">.
If that assumption is correct, I suggest that you add a differential equation for each <img src="https://render.githubusercontent.com/render/math?math=k^*"> to your populations:
`d/dt * k_star = (k*(2*p_std - ext_std*k) - k_star)/tau_k`
This equation will converge to eq. 5 of David and Friston (2003) in the limit <img src="https://render.githubusercontent.com/render/math?math=\tau_k \rightarrow 0">. But in practice, you probably do not need to choose <img src="https://render.githubusercontent.com/render/math?math=\tau_k"> that small.
Then you are left with the problem of approximating the standard deviation of the input `ext_std`. I suggest to use 
<img src="https://render.githubusercontent.com/render/math?math=\sigma(x) = \sqrt{|x^2| - |x|^2}"> here, and additionally implement two differential equations that approximate the averages over a short history of `x`, i.e.
`d/dt * x_avg = (x - x_avg) / tau_x`
and 
`d/dt * x_sq = (x**2 - x_sq) / tau_x`
where <img src="https://render.githubusercontent.com/render/math?math=\tau_x"> controls the time scale at which the average is calculated. Not entirely sure whether this delivers correct results, but my first guess is that it should be more appropriate than that helper variable scheme.

Best, Richard

**Comment by ffriese** [comment]
Dear @Richert,
once again thanks for your incredibly fast and informed reply. Your support is invaluable to me.

As I wanted to give you something to look at as fast as possible, the following example is not perfectly "minimal" and contains some unnecessarily complex/generic (and therefore possibly harder to immediately grasp) code segments, but I hope that does not hinder you too much - otherwise let me know and I'll invest some more time to strip it down to the basics.

```python
import itertools

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
from mne.time_frequency import psd_array_multitaper

from pyrates.frontend import OperatorTemplate, NodeTemplate, CircuitTemplate
from pyrates.utility.grid_search import grid_search


class SimulationResult:
    def __init__(self, time_series, results_map, sampling_step_size, param_map):
        self.time_series = time_series
        self.results_map = results_map
        self.sampling_step_size = sampling_step_size
        self.param_map = param_map

    def to_dict(self):
        return {
            'time_series': self.time_series,
            'results_map': self.results_map,
            'sampling_step_size': self.sampling_step_size,
            'param_map': self.param_map
        }

    @staticmethod
    def from_dict(data: dict):
        return SimulationResult(**data)


def create_pro(name):
    return OperatorTemplate(
        name=name, path='',
        equations=["m_out = m_max / (1 + exp(r*(V_thr - PSP)))"],
        variables={'m_out': {'default': 'output'},
                   'PSP': {'default': 'input'},
                   'V_thr': {'default': 6e-3},
                   'm_max': {'default': 5.},
                   'r': {'default': 560.0}},
        description="sigmoidal potential-to-rate operator")


def create_rpo(name, tau_0, tau_1, h_0, h_1):
    return OperatorTemplate(
        name=name, path='',
        equations=['d/dt * I_0 = X_0',
                   'd/dt * X_0 = H_0/tau_0 * m_in - (1./tau_0)^2. * I_0 - 2. * 1./tau_0 * X_0',
                   'd/dt * I_1 = X_1',
                   'ext = ext',
                   'd/dt * X_1 = H_1/tau_1 * m_in - (1./tau_1)^2. * I_1 - 2. * 1./tau_1 * X_1',
                   'PSP = w*I_0 + (1-w)*I_1'],
        variables={'PSP': {'default': 'output'},
                   'I_0': {'default': 'variable'},
                   'I_1': {'default': 'variable'},
                   'X_0': {'default': 'variable'},
                   'X_1': {'default': 'variable'},
                   'm_in': {'default': 'input'},
                   'ext': {'default': 'input'},
                   'w': {'default': 0.8},
                   'tau_0': {'default': tau_0},
                   'tau_1': {'default': tau_1},
                   'H_0': {'default': h_0},
                   'H_1': {'default': h_1}},
        description="rate-to-potential operator")


def single_subpoulation():
    """
        Creates a Jansen-Rit Circuit with two subpopulations in each rate-to-potential operator
         as proposed by David and Friston
    """
    pro = create_pro(name='PRO')
    pro_pc = create_pro(name='PRO_pc')

    # subpopulation parameters taken from the paper
    tau_e = [10.8e-3, 4.6e-3]
    tau_i = [22e-3, 2.9e-3]

    h_e = [3.25e-3 * 10e-3 / tau for tau in tau_e]
    h_i = [-22e-3 * 20e-3 / tau for tau in tau_i]

    rpo_e = create_rpo('RPO_e', tau_e[0], tau_e[1], h_e[0], h_e[1])
    rpo_e_pc = rpo_e.update_template('RPO_e_pc', '',
                                     equations={'replace': {
                                         'm_in': '(m_in+u)'}},  # normally more complex equation
                                     variables={'u': {'default': 220.0}
                                                })

    rpo_i = create_rpo('RPO_i', tau_i[0], tau_i[1], h_i[0], h_i[1])

    ein = NodeTemplate(name="EIN", path='', operators=[pro, rpo_e])
    iin = NodeTemplate(name="IIN", path='', operators=[pro, rpo_e])
    pc = NodeTemplate(name="PC", path='', operators=[pro_pc, rpo_e_pc, rpo_i])

    return ein, iin, pc


def subpopulation_model(areas):
    """
        Creates a Jansen-Rit Circuit with two subpopulations in each rate-to-potential operator
         as proposed by David and Friston
    """
    nodes = {}
    edges = []
    for area in areas:
        nodes[f'EIN{area}'], nodes[f'IIN{area}'], nodes[f'PC{area}'] = single_subpoulation()
        edges.append((f"PC{area}/PRO_pc/m_out", f"EIN{area}/RPO_e/m_in", None, {'weight': 135.}))
        edges.append((f"EIN{area}/PRO/m_out", f"PC{area}/RPO_e_pc/m_in", None, {'weight': 108.}))
        edges.append((f"PC{area}/PRO_pc/m_out", f"IIN{area}/RPO_e/m_in", None, {'weight': 33.75}))
        edges.append((f"IIN{area}/PRO/m_out", f"PC{area}/RPO_i/m_in", None, {'weight': 33.75}))
        for other_area in areas:
            if other_area != area:
                edges.append((f"PC{area}/PRO_pc/m_out", f"PC{other_area}/RPO_e_pc/ext",
                              None, {'weight': 0.0, 'delay': 0.001, 'spread': 0.0005}))
    jrc = CircuitTemplate(
        name="JRC", nodes=nodes,
        edges=edges,
        path='')
    return jrc


def simulate(template, param_map, param_grid, step_size, sampling_step_size, seconds, areas=2) -> SimulationResult:
    """
        Performs a grid search for w (mix the subpopulations)
    """

    def opname(connectivity_shortcode):
        return 'e_pc' if connectivity_shortcode == 'e' else 'i'

    size = (int(np.round(seconds / step_size, decimals=0)), 1)
    results, results_map = grid_search(circuit_template=template,
                                       param_grid=param_grid,
                                       param_map=param_map,
                                       simulation_time=seconds,
                                       step_size=step_size,
                                       sampling_step_size=sampling_step_size,
                                       inputs={f'PC{area}/RPO_e_pc/u':
                                                   np.random.normal(loc=220.0, scale=22.0, size=size)
                                               for area in range(areas)},
                                       outputs={
                                           **{f'I{a[0]}_pc{conn}{a[1]}':
                                              f'PC{a[1]}/RPO_{opname(conn)}/I_{a[0]}' for a, conn in
                                              itertools.product(itertools.product([0, 1],
                                                                                  range(areas)),
                                                                ['i', 'e'])},
                                           **{f'w_{a}': f'PC{a}/RPO_e_pc/w' for a in range(areas)},
                                       },
                                       init_kwargs={'backend': 'numpy', 'solver': 'scipy', 'step_size': step_size,
                                                    'in_place': True},
                                       verbose=False,
                                       permute_grid=False)
    for rw, key in enumerate(results_map.index):
        for i, row in enumerate([rw * areas, rw * areas + 1]):
            psp_0 = results.loc[:, (f'I0_pce{i}', key)] + results.loc[:, (f'I0_pci{i}', key)]
            psp_1 = results.loc[:, (f'I1_pce{i}', key)] + results.loc[:, (f'I1_pci{i}', key)]
            w = results_map[f'w_{i}'][key]
            results[f'v{i}'] = psp_0 * w + psp_1 * (1 - w)

    return SimulationResult(results, results_map, sampling_step_size, param_map)


def simulate_with_params(variables) -> SimulationResult:
    param_grid, param_map = create_param_map(variables)
    areas = 2
    return simulate(
        template=subpopulation_model(range(areas)),
        param_grid=param_grid, param_map=param_map,
        step_size=1e-4,  # choosing 1e-3 here does not really make a difference
        sampling_step_size=1e-3,
        seconds=variables['seconds'],
        areas=areas
    )


def plot(simulation_result: SimulationResult, areas=2):
    """
        Plot the resulting signals and their spectrum
    """

    fig = plt.figure(figsize=(8, 12))
    fig.suptitle(f'Fig.6')
    gs = fig.add_gridspec(len(simulation_result.results_map) * areas, 2)

    def multitaper(data, fs, freq_range, bandwidth=None):
        power, _f = psd_array_multitaper(data, fs, bandwidth=bandwidth, fmin=freq_range[0], fmax=freq_range[1],
                                         adaptive=True,
                                         normalization='full', verbose=0)
        return _f, power

    def filter_params_for_plot(all_params, given_area, given_plot_type):

        in_areas = {k: simulation_result.param_map[k].get(
            'plot_filter', {'area': given_area}).get('area', given_area) == given_area for k, _ in all_params}
        in_plot_types = {k: simulation_result.param_map[k].get(
            'plot_filter', {'plot_type': given_plot_type}).get('plot_type', given_plot_type) == given_plot_type for k, _
                         in all_params}

        return [(k, val) for k, val in all_params if in_areas[k] and in_plot_types[k]]

    for rw, key in enumerate(simulation_result.results_map.index):

        # get infos from results map
        parameters = [simulation_result.results_map.at[key, c] for c in simulation_result.results_map.columns]

        # calculate combined LFP
        for area, row in enumerate([rw * areas, rw * areas + 1]):
            v_lb = "\n".join([f'${key} = {w}$' for key, w in
                              filter_params_for_plot(
                                  list(zip(simulation_result.results_map.columns, parameters)), area, 'time_series')])

            v = simulation_result.time_series[f'v{area}']
            ax = fig.add_subplot(gs[row, 0])
            ax.plot(simulation_result.time_series.index, v, label=f"$\mathbf{{Area {area + 1} Timeseries}}$\n{v_lb}",
                    color=f'C{row}')
            ax.legend(loc='upper right')
            ax.margins(0.0)

            ax2 = fig.add_subplot(gs[row, 1])
            ax2.margins(0.0)
            ax2.plot(*multitaper(data=np.squeeze(v.values), fs=1 / simulation_result.sampling_step_size,
                                 freq_range=(0.0, 100)),
                     label=f"$\mathbf{{Area {area + 1} PSD}}$\n{v_lb}", color=f'C{row}')
            ax2.legend(loc='upper right')
            row += 1

    plt.tight_layout()
    plt.show()


def create_param_map(variables):
    param_grid = {}
    param_map = {}

    def inv(_idx, add=0):
        return [1, 0][_idx] + add

    if 'delay' in variables:
        param_grid[r'\delta'] = variables.get('delay')
        param_map[r'\delta'] = {'vars': ['delay'],
                                'edges': [("PC0", "PC1"),
                                          ("PC1", "PC0")]}

    for idx, w in enumerate(variables.get('w', [])):
        param_grid[f'w_{idx}'] = [w]
        param_map[f'w_{idx}'] = {'vars': ['RPO_e/w', 'RPO_e_pc/w', 'RPO_i/w'],
                                 'nodes': [f'PC{idx}', f'EIN{idx}', f'IIN{idx}'],
                                 'plot_filter': {'area': idx}}

    return param_grid, param_map


def sim_and_plot(variables, start_msec=None, stop_msec=None):
    for var in variables:
        simulation_result = simulate_with_params(var)
        simulation_result.time_series = simulation_result.time_series.iloc[start_msec:stop_msec]
        plot(simulation_result)
    # plt.show()

if __name__ == '__main__':
    params = [

        {'seconds': 2.0, 'w': [0.2, 0.8], 'delay': [0.001]},
        {'seconds': 2.0, 'w': [0.8, 0.2], 'delay': [0.001]}

    ]
    sim_and_plot(params, 1000)

```

Best, Felix

**Comment by Richert** [comment]
Dear @ffriese 

I am happy to help!

Regarding your example: I just published a new release of PyRates, where I fixed a bug that sometimes occurred for specific `CircuitTemplate` configurations when using `grid_search` and edge delays. Could you please check whether this bug-fix solved your problem by chance? Should the problem persist - could you give me the additional information, what kind of output you would expect from the script you provided, if it would be working correctly?

**Comment by ffriese** [comment]
Hello @Richert,
unfortunately the issue still persists with you new version.
When I run the script just as I posted it above, I get the following two figures:

w= [0.2, 0.8] | w= [0.8, 0.2]
-------------|----------------
![afterfix1](https://user-images.githubusercontent.com/28440404/121534047-25082180-ca01-11eb-809a-7d7bd8847725.png) |![afterfix2](https://user-images.githubusercontent.com/28440404/121534079-2d605c80-ca01-11eb-8882-a63a3a726ba5.png)


I would expect these graphs to be identical (except for rows being switched), as there is no functional connection defined between these two independent areas, except for a bi-directional edge with weight 0.0, that is connected to a variable which is not used in any of the equations that determine the output. Instead, at least in the first condition (I cannot think of a reason why order would matter here, but it appears to do) the two areas which should produce entirely different signals, seem to "sync-up" somehow, or produce an incorrect signal for some other reason.

**Comment by Richert** [comment]
Dear @ffriese 

I have released a new version of PyRates that should fix your issue. There was a problem that sometimes could cause a mix-up between edges of a network node that formed edges via both delayed and non-delayed outputs.
Independent of that, I also implemented that zero-weight edges are removed from the network early during compilation, no matter whether they have a delay defined on them or not. This should also increase the compilation speed a bit. 

When I tested your script, it now produces two very similar timeseries for the two different `w` configurations, with the rows being flipped. I expect the remaining differences to be caused by the random input to the system. Let me know whether the recent changes to PyRates solved your problem.

Best, Richard

**Comment by ffriese** [comment]
Dear @Richert,
yes, that did the trick! 👍 
Thanks a lot!
I am positive that the edge-issue is resolved by this.

In regard to your approach to the calculation of k*, I still have a few question though.
As far as I understand, the equations you provided sum up to the following so far:

````python

variables = [
    'ext': {'default': 'input'},
    'ext_std': {'default': 'variable'},
    'p_std': {'default': '22'},
    'k_star': {'default': 'variable'},
    'k': {'default': 'variable'},
    'tau_k': {'default': 'variable'},
    'x_avg': {'default': 'variable'},
    'x_sq': {'default': 'variable'},
]

equations = [
    'd/dt * k_star = (k*(2*p_std - ext_std*k) - k_star)/tau_k',
    'd/dt * x_avg = (ext - x_avg) / tau_x',
    'd/dt * x_sq = (ext**2 - x_sq) / tau_x'
]

````
and

````python
equations={'replace': {'m_in': '(m_in+(ext*k_star)+(u*(1-k)))'}}
````


what I fail to understand for the moment is how to express the crucial equation for ext_std as a differential equation.
I suppose I am being blind here...
